Tela1:
    TargetPicture:
        id: _t1
        wid: 'wid-t1'
        pos: 800, 200
        size: 320, 240
        size_hint_x: None
        size_hint_y: None
        canvas.before:
            Color:
                rgb: self.rbgcolor
            Rectangle:
                pos: self.pos
                size: self.size
        Imagem:
            id: _ti1
            wid: 'wid-ti1'
            source: 'figuras/ordem1/a_1.jpg'
            pos: self.parent.pos[0] + ((self.parent.width - self.width) / 2 ), self.parent.pos[1] + ((self.parent.height - self.height) / 2 )
            size: self.parent.width * 0.90, self.parent.height * 0.90
            fit_mode: 'fill'
    SourcePicture:
        id: _s1
        wid: 'wid-s1'
        pos: 80, 200
        size: 320, 240
        size_hint_x: None
        size_hint_y: None
        Imagem:
            id: _si1
            wid: 'wid-si1'
            source: 'figuras/ordem1/a_2.jpg'
            pos: self.parent.pos[0] + ((self.parent.width - self.width) / 2 ), self.parent.pos[1] + ((self.parent.height - self.height) / 2 )
            size: self.parent.width * 0.90, self.parent.height * 0.90
            fit_mode: 'fill'