<TelaTesteTTAB>:
    name: 'telatesteTTab'
    TargetPicture:
        id: _t1
        wid: 'wid-t1'
        pos: 800, 200
        size: 320, 240
        size_hint_x: None
        size_hint_y: None
        canvas.before:
            Color:
                rgb: self.rbgcolor
            Rectangle:
                pos: self.pos
                size: self.size
        Imagem:
            id: _ti1
            wid: 'wid-ti1'
            source: self._imagem
            pos: self.parent.pos[0] + ((self.parent.width - self.width) / 2 ), self.parent.pos[1] + ((self.parent.height - self.height) / 2 )
            size: self.parent.width * 0.90, self.parent.height * 0.90
            fit_mode: 'fill'
    TargetPicture:
        id: _t2
        wid: 'wid-t2'
        pos: 800, 840
        size: 320, 240
        size_hint_x: None
        size_hint_y: None
        canvas.before:
            Color:
                rgb: self.rbgcolor
            Rectangle:
                pos: self.pos
                size: self.size
        Imagem:
            id: _ti2
            wid: 'wid-ti2'
            source: self._imagem
            pos: self.parent.pos[0] + ((self.parent.width - self.width) / 2 ), self.parent.pos[1] + ((self.parent.height - self.height) / 2 )
            size: self.parent.width * 0.90, self.parent.height * 0.90
            fit_mode: 'fill'
    TargetPicture:
        id: _t3
        wid: 'wid-t3'
        pos: 800, 1480
        size: 320, 240
        size_hint_x: None
        size_hint_y: None
        canvas.before:
            Color:
                rgb: self.rbgcolor
            Rectangle:
                pos: self.pos
                size: self.size
        Imagem:
            id: _ti3
            wid: 'wid-ti3'
            source: self._imagem
            pos: self.parent.pos[0] + ((self.parent.width - self.width) / 2 ), self.parent.pos[1] + ((self.parent.height - self.height) / 2 )
            size: self.parent.width * 0.90, self.parent.height * 0.90
            fit_mode: 'fill'
    SourcePicture:
        id: _s1
        wid: 'wid-s1'
        pos: 80, 200
        size: 320, 240
        size_hint_x: None
        size_hint_y: None
        Imagem:
            id: _si1
            wid: 'wid-si1'
            source: self._imagem
            pos: self.parent.pos[0] + ((self.parent.width - self.width) / 2 ), self.parent.pos[1] + ((self.parent.height - self.height) / 2 )
            size: self.parent.width * 0.90, self.parent.height * 0.90
            fit_mode: 'fill'
    SourcePicture:
        id: _s2
        wid: 'wid-s2'
        pos: 80, 840
        size: 320, 240
        size_hint_x: None
        size_hint_y: None
        Imagem:
            id: _si2
            wid: 'wid-si2'
            source: self._imagem
            pos: self.parent.pos[0] + ((self.parent.width - self.width) / 2 ), self.parent.pos[1] + ((self.parent.height - self.height) / 2 )
            size: self.parent.width * 0.90, self.parent.height * 0.90
            fit_mode: 'fill'
    SourcePicture:
        id: _s3
        wid: 'wid-s3'
        pos: 80, 1480
        size: 320, 240
        size_hint_x: None
        size_hint_y: None
        Imagem:
            id: _si3
            wid: 'wid-si3'
            source: self._imagem
            pos: self.parent.pos[0] + ((self.parent.width - self.width) / 2 ), self.parent.pos[1] + ((self.parent.height - self.height) / 2 )
            size: self.parent.width * 0.90, self.parent.height * 0.90
            fit_mode: 'fill'